from .legalPersonSchema import LegalPersonSchema
from .userSchema import UserSchema
from .partnerSchema import PartnerSchema
from .eventSchema import EventSchema
from .genreTypesSchema import GenreTypeSchema
from .categorySchema import CategorySchema
from .ticketSchema import TicketSchema
from .lotsSchema import LotSchema
from .physicalPersonSchema import PhysicalPersonSchema
from .orderSchema import OrderSchema
from .rulesEventSchema import RulesEventSchema
from .termsEventSchema import TermsEventSchema
from .userAccessTypesSchema import UserAccessTypesSchema
from .userTypesSchema import UserTypesSchema